# Generated by Django 5.1.2 on 2024-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('download_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد دفعات بارگیری')),
                ('content', models.FileField(blank=True, null=True, upload_to='gifts/', verbose_name='ویدئو یا فایل دانلود')),
                ('gift_type', models.CharField(choices=[('FI', 'File'), ('VI', 'Video')], default='FI', max_length=2, verbose_name='نوع هدیه')),
            ],
            options={
                'verbose_name': 'هدیه',
                'verbose_name_plural': 'هدایا',
            },
        ),
    ]
