# Generated by Django 5.1.2 on 2024-10-31 13:22

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_customer_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bot.customer', verbose_name='کاربر')),
            ],
        ),
    ]
