# Generated by Django 5.1.2 on 2024-10-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('token', models.CharField(max_length=300, verbose_name='توکن')),
                ('welcome_message', models.TextField(verbose_name='پیام خوش آمدگویی')),
                ('welcome_picture', models.ImageField(upload_to='media/pictures/', verbose_name='تصویر خوش آمدگویی')),
            ],
            options={
                'verbose_name': 'ربات',
                'verbose_name_plural': 'ربات ها',
            },
        ),
    ]
