# Generated by Django 5.1.2 on 2024-10-31 12:56

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('chat_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='آی دی چت')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری')),
                ('has_username', models.BooleanField(default=False, verbose_name='نام کاربری دارد')),
                ('has_recieved_gift', models.BooleanField(default=False, verbose_name='هدیه دریافت کرده')),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه')),
                ('has_phone_number', models.BooleanField(default=False, verbose_name='شماره همراه دارد')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='عکس پروفایل')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد یکبار مصرف')),
                ('created', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateField(verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'کاربر تلگرام',
                'verbose_name_plural': 'کاربران تلگرام',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('telegram_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان در تلگرام')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/posts/', verbose_name='تصویر شاخص')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
            },
        ),
    ]
