# Generated by Django 5.1.2 on 2024-11-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_customer_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='telegram_title',
        ),
    ]
