# Generated by Django 5.1.2 on 2024-11-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_post_telegram_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5),
        ),
    ]
