# Generated by Django 5.1.2 on 2024-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link_to_website',
            field=models.CharField(max_length=255, verbose_name='لینک محصول در وبسایت'),
        ),
    ]
